export const FETCH_IMAGES_LIST = "FETCH_IMAGES_LIST"
export const FETCH_IMAGES_LIST_START = "FETCH_IMAGES_LIST_START"
export const FETCH_IMAGES_LIST_SUCCESS = "FETCH_IMAGES_LIST_SUCCESS"
export const FETCH_IMAGES_LIST_FAIL = "FETCH_IMAGES_LIST_FAIL"

export const FETCH_WORDS_LIST = "FETCH_WORDS_LIST"
export const FETCH_WORDS_LIST_START = "FETCH_WORDS_LIST_START"
export const FETCH_WORDS_LIST_SUCCESS = "FETCH_WORDS_LIST_SUCCESS"
export const FETCH_WORDS_LIST_FAIL = "FETCH_WORDS_LIST_FAIL"
