export const FETCH_WORD_IMAGES = "FETCH_WORD_IMAGES"
export const FETCH_WORD_IMAGES_START = "FETCH_WORD_IMAGES_START"
export const FETCH_WORD_IMAGES_SUCCESS = "FETCH_WORD_IMAGES_SUCCESS"
export const FETCH_WORD_IMAGES_FAIL = "FETCH_WORD_IMAGES_FAIL"

export const FETCH_WORD_DEFINITION = "FETCH_WORD_DEFINITION"
export const FETCH_WORD_DEFINITION_START = "FETCH_WORD_DEFINITION_START"
export const FETCH_WORD_DEFINITION_SUCCESS = "FETCH_WORD_DEFINITION_SUCCESS"
export const FETCH_WORD_DEFINITION_FAIL = "FETCH_WORD_DEFINITION_FAIL"
